### PR TITLE
aligning mantlemint with latest classic core release v1.1.0

### PR DESCRIPTION
**Pull request by inon-man**
## Description
This PR aligns mantlemint with [classic-terra/core v1.1.0](https://github.com/classic-terra/core/releases/tag/v1.1.0)

## Changes
* use classic-terra/core as module path instead of using go mod replace
* use the same cosmos-sdk version of classic-terra/core
* upgrade tm-db to v0.6.7-performance.3. It's been tested by full sync from the genesis, but make sure the OS open max files to be >= 65535 as introduced in [Terra Docs](https://docs.terra.money/full-node/run-a-full-terra-node/set-up-production/#increase-limit-of-file-descriptors-per-process)

### CODE REVIEW

**Review by javiersuweijie — APPROVED** [review]
LGTM

**Comment by ZaradarBH** [comment]
@Jared-TFL you seems to be stating on Twitter that there is something wrong with our PR @ https://twitter.com/ZaradarBH/status/1631696396746145792 . Could anyone in TFL please give us some actual feedback on what the issues are so we can fix them and get the PR approved? Thx.

**Comment by Jared-TFL** [comment]
@alecande11 I asked you to comment on this earlier. Please respond with your feedback.

**Review by ZaradarBH — APPROVED** [review]

**Comment by ZaradarBH** [comment]
I have aligned the go.mod & go.sum conflicts. @inon-man please verify that these changes work as intended

**Pull request merged**
